### ISSUE TITLE
Inconsistency in exercise instructions and code/solution: number of hidden units

### ISSUE THREAD

**Issue by SilverViking** [JorisRoels/deep-learning-biology#4]
2020-dlb-1-neural-networks.ipynb section 3, the exercise instructions say "The first layer will be a fully connected layer with relu activation that transforms the input features to a 256 dimensional (hidden) feature vector representation." but the partial code and the solution uses 512 hidden units.

**Comment by JorisRoels** [comment]
Solved in commit 22442127d41d2960d6761b4066b24ee969a3bdc0
